variables:
  baseName: knyadb3600109
  env: dev
  resourcegroup: rg-wuswedencentrals2-$(baseName)-dev
  vnetresourcegroup: rg-swedencentral-$(baseName)-net-dev
  transitresourcegroup: rg-swedencentral-$(baseName)-trans-dev
  vnetname: $(baseName)$(env)-vnet
  location: swedencentral
