variables:
  baseName: knnyadb3600129
  env: dev
  resourcegroup: rg-swedencentral-$(baseName)-dev
  vnetresourcegroup: rg-swedencentral-$(baseName)-net-dev
  transitresourcegroup: rg-swedencentral-$(baseName)-trans-dev
  vnetname: $(baseName)$(env)-vnet
  location: swedencentral
